### PR TITLE
Bumped source and target compatibility to Java 1.8

### PR DESCRIPTION
**Pull request by peterdemaeyer**

### CODE REVIEW

**Comment by peterdemaeyer** [comment]
The Travis build with Java 1.7 will fail of course.

**Comment by nik9000** [comment]
I'm just someone random in the internet, but this looks like a good change to me. Maybe drop the java 7 config from Travis in this pr too?

The raw types make me sad, but it's a small price to pay for it to be much much easier to contribute. 

From a purely semver standpoint this is a breaking change, I think. But I imagine most folks are off of 7. I'm not even sure how to download it at this point....

**Comment by peterdemaeyer** [comment]
> I'm just someone random in the internet, but this looks like a good change to me. Maybe drop the java 7 config from Travis in this pr too?
> 
> The raw types make me sad, but it's a small price to pay for it to be much much easier to contribute.
> 
> From a purely semver standpoint this is a breaking change, I think. But I imagine most folks are off of 7. I'm not even sure how to download it at this point....

I removed the Java 7 Travis build configuration.

**Comment by peterdemaeyer** [comment]
On top of it, Travis CI has moved from .org to .com, so Travis builds are no longer working.
As a workaround, I set up my own Travis for my fork, but now Oracle JDK builds are failing.

**Comment by rjmunro** [comment]
Ideally there would be a last release on version Java 7 with whatever we have now, then this 1.8 bump can be merged and a whole pile of new Java 8 features can be added.

**Comment by tumbarumba** [comment]
Fixed in #411

**Pull request closed without merging**
