### PR TITLE
Remove unused imports

### PR DESCRIPTION
**Pull request by mureinik**

### CODE REVIEW

**Comment by nhojpatrick** [comment]
@mureinik happy to get merged if rebased from master as `hamcrest-core` and `hamcrest-library` has been merged into `hamcrest` so can't currently merge in.

**Comment by mureinik** [comment]
@nhojpatrick wow, I forgot about this PR completely :-)

Rebased and ready for review/merge.

**Comment by nhojpatrick** [comment]
@mureinik i forgot i became a contributor... distracted by a few other open source projects...

cheers for pr

**Comment by mureinik** [comment]
@nhojpatrick didn't mean that as a dig, and sorry if it may have come out like that.
thanks for taking care of this!

**Pull request merged**
