### PR TITLE
Added @SafeVarargs annotation to Matchers.* methods

### PR DESCRIPTION
**Pull request by dkomanov**

### CODE REVIEW

**Comment by dkomanov** [comment]
up?

**Comment by dkomanov** [comment]
up?

**Comment by mhfrantz** [comment]
:+1:

**Comment by nbruno** [comment]
This would eliminate warnings emitted when using generics with the matchers in the PR. Any reason why this hasn't been merged already?

**Comment by erosb** [comment]
@nbruno this project is quite dying (see other issues and PRs), at least looking for a new maintainer.

**Comment by sf105** [comment]
Done

**Pull request closed without merging**
