### PR TITLE
generic static factory methods for IsAnything matcher

### PR DESCRIPTION
**Pull request by innokenty**

### CODE REVIEW

**Comment by sf105** [comment]
Can you write up an example where this would be useful? Thx

**Comment by innokenty** [comment]
So it just doesn't complain about unsafe generics..

**Comment by sf105** [comment]
Just tried it in a test (Java 7) and not seeing any problems. Can you help?

**Comment by innokenty** [comment]
I don't remember already :smiley: 
It's like if you write
```java
String s = "";
assertThat(s, is(anything()));
```
IDEA should complain about generics mismatch. But you can just close it if it doesn't...

**Comment by sf105** [comment]
Works for me. Please reopen with an example if I'm wrong.

**Pull request closed without merging**
