### PR TITLE
Make possible to change `includeComparatorInDescription`.

### PR DESCRIPTION
**Pull request by andreoss**
Add method for charging this flag for custom comparators.

### CODE REVIEW

**Comment by nhojpatrick** [comment]
Going to try and kick start hamcrest, so if you want to get it merged, please rebase from the branch `v2.3-candidates`.
Still trying to understand how has permissions to perform a release.

**Comment by andreoss** [comment]
@nhojpatrick Done.

**Comment by andreoss** [comment]
@nhojpatrick Ping

**Comment by andreoss** [comment]
@nhojpatrick Ping

**Pull request closed without merging**
