### PR TITLE
change signature of all comparator methods

### PR DESCRIPTION
**Pull request by bjrke**
issue: https://github.com/hamcrest/JavaHamcrest/issues/328

### CODE REVIEW

**Review by hakanai — APPROVED** [review]
Seems right to me.

**Comment by bjrke** [comment]
> Seems right to me.

@hakanai I am not allowed to merge this PR, what will happen now with this PR?

**Comment by hakanai** [comment]
You’d need someone with the privileges to come through and merge it.

**Comment by bjrke** [comment]
@nhojpatrick can you merge this PR?

**Comment by bjrke** [comment]
bump

**Comment by bjrke** [comment]
I dropped the dependency to hamcrest in our project and therefore will close this pull request. Feel free to reopen it if you need it. I don't need hamcrest anymore.

**Pull request closed without merging**
